#!/public/frasergen/PUB/software/Anaconda/anaconda3-3d/envs/report/bin/Rscript
library(bookdown)
library(fraserReport)
library(knitr)
library(kableExtra)
library(yaml)

if (!file.exists("report.yaml")){print("[ERROR] cannot access to report.yaml"); q()}
inconf <- yaml.load_file("report.yaml")
if (inconf$loop=="mustache"){
	rmd_file <- "/public/frasergen/3D/pipeline/Interactome/hic3_workflow/report/single_report_animal.rmd"
} else if (inconf$loop=="fithic"){
	rmd_file <- "/public/frasergen/3D/pipeline/Interactome/hic3_workflow/report/single_report_plant.rmd"
} else {
	print("[ERROR] cannot determine whether it is an animal or a plant through the loop information."); q()
}

if (file.exists("_main.Rmd")) file.remove("_main.Rmd")
file.copy("/public/frasergen/3D/pipeline/Interactome/hic3_workflow/report/src/", ".", recursive=TRUE)
file.copy("/public/frasergen/3D/pipeline/Interactome/hic3_workflow/report/css/", ".", recursive=TRUE)
file.copy(rmd_file, "single_report.rmd")

bookdown::render_book("single_report.rmd", output_format="html_document", 
		output_file="single_sample_report.html", output_dir=".")
#if (file.exists("single_report.rmd")) file.remove("single_report.rmd")
