#!/public/frasergen/PUB/software/python/Python-3.7.10/bin/python3.7
#-*- coding: utf-8 -*-

import deeptools.misc
from computeMatrix import main
import sys

if __name__ == "__main__":
    args = None
    if len(sys.argv) == 1:
        args = ["--help"]
    elif len(sys.argv) == 2 and sys.argv[1] != '--version':
        sys.argv.append("--help")
    main(args)
